
[bibliography]
== Normative References

* [[[RFC2119,RFC 2119]]]
* [[[RFC4791,RFC 4791]]]
* [[[RFC4918,RFC 4918]]]
* [[[RFC5545,RFC 5545]]]
* [[[RFC5546,RFC 5546]]]
* [[[RFC8174,RFC 8174]]]
* [[[RFC9073,RFC 9073]]]
* [[[RFC9074,RFC 9074]]]
* [[[RFC9253,RFC 9253]]]

[bibliography]
== Informative References

* [[[BPMN,OMG BPMN 2.0.2]]], Object Management Group, Business Process Model and Notation, Version 2.0.2, December 2013

* [[[TARCH,nofetch((CalConnect Task Architecture V1.0)]]],
span:surname[Apthorp], span:initials[A.],
span:surname[Daboo], span:initials[C.],
span:surname[Douglass], span:initials[M.],
span:title[_CalConnect, Task Architecture V1.0_],
span:uri.src[https://www.calconnect.org/architectures/Task%20Architecture%201.0.pdf].
span:type[book]

* [[[WfRP,nofetch(WfRP)]]],
span:surname[Russell], span:initials[N.],
span:surname[ter Hofstede], span:initials[A.H.M.],
span:surname[Edmond], span:initials[T.],
span:surname[van der Aalst,], span:initials[W.M.P.],
span:title[_Workflow Resource Patterns_],
span:publisher[Eindhoven University of Technology],
span:date[2004],
span:uri.src[http://www.workflowpatterns.com/patterns/resource/].
span:type[book]
