[[task-specification]]

== Task Specification

The specification of tasks must be semantically explicit in order for
them to be managed within the context of a business process or project,
and be understood by both humans and IT systems. The current
"VTODO" calendar component only provides for simple ad-hoc tasks or
'to do' lists, and is therefore extended by this specification as follows:

Task type:: explicitly what type of task is to be performed is identified.

Task context and relationships:: how a specific task relates to other tasks
and other objects that need to be understood for the effective execution of a task.

Task specific data:: the form and content of domain data provided as input to a task and/or that may be output from a task.

Organizer and attendee:: recognizes that a task "Organizer" or "Attendee" can be an automated system.

=== Task type

The <<RFC9253>> "CONCEPT" property is used to identify the type of task, for example;

[source]
----
CONCEPT:http://example.com/task/delivery
----

=== Task Context and Relationships

The <<RFC9253>> "LINK" property specifies a link to external information, which may be context to the task. For example:

[source]
----
LINK;LINKREL=SOURCE:http://example.com/package/1234567890

LINK;LINKREL=describedby:mid:752142.141482.307E5@mx123.example.com
----

The external information may be data to be manipulated in performing the task. See <<task-specific-data>>.

The <<RFC9253>> "REFID" property is used to identify a key
used to group tasks by that key.

[source]
----
REFID:Manhattan

REFID:1234567890
----

Extensions to the "RELATED-TO" property defined in <<RFC9253>> allow temporal relationships
between tasks as found in project management to be specified as well as parent/child
relationships and dependencies (DEPENDS-ON). Tasks (VTODO calendar components) may also be related to other
calendar components; for example to a "VEVENT" calendar component to block time to perform a task.

[[task-specific-data]]
=== Task Specific Data

The "LINK" property can be used to relate a domain specific service to the task. For example, it might be a URI pointing to a web page where the status of the task can be directly manipulated.

[source]
----
LINK;LINKREL="vacation-system";VALUE=URI:
 http://example.com/vacation-approval?id=1234
----

Additionally, it might be used to link data specific to the task, for example an electronic copy
of a signature taken to confirm delivery of a package.

[source]
----
LINK;LINKREL="electronic-signature";VALUE=URI:
 http://example.com/delivery/sig1234.jpg
----
