[[status-reporting]]

== Status Reporting

=== Improved granularity in status reporting information

This document defines a new "VSTATUS" calendar component (see section <<vstatus>>)
that can be used to
group related information about the status of the task. This might include
information on why, the "REASON" property and when, the "DTSTAMP" property, a status has changed.
In addition, new status values are specified to
provide for task suspension, failure and preparation.

[source]
----
BEGIN:VSTATUS
STATUS:FAILED
REASON:https://example.com/reason/delivery-failed
SUBSTATE:ERROR
DTSTAMP:20130212T120000Z
COMMENT:Breakdown
END:VSTATUS
----

=== Comments associated to reasons and status changes

Multiple comments and reasons may have the same status. As situations
change further "VSTATUS" calendar components can be added to provide additional
information.

[source]
----
CONCEPT:https://example.com/task/delivery
BEGIN:VSTATUS
STATUS:FAILED
SUBSTATE:ERROR
DTSTAMP:20220212T104900Z
COMMENT:Out of time
END:VSTATUS
BEGIN:VSTATUS
STATUS:FAILED
COMMENT:Traffic Accident on E44
REASON:https://example.com/reason/traffic
DTSTAMP:20220212T110451Z
END:VSTATUS
BEGIN:VSTATUS
STATUS:FAILED
COMMENT:Arrived after office hours
REASON:https://example.com/reason/closed
DTSTAMP:20220212T180451Z
END:VSTATUS
----

Note that the "VSTATUS" calendar component is not intended to be used as a history
of changes to a tasks properties. The purpose of the "VSTATUS"
calendar component is only to document changes related to fulfilling
the tasks

=== Relating reason and comments to "ATTENDEE" property status changes.

The <<RFC9073>> "PARTICIPANT" calendar component can be used to provide additional
information about why an "ATTENDEE" property participation status has changed.
The "COMMENT" property can also
be used to include additional human-readable information about why the
associated "STATUS" or "ATTENDEE" property changed. For example, if a driver
failed to deliver a package
because of a puncture it might be expressed as

[source]
----
ATTENDEE;PARTSTAT=FAILED:mailto:xxx@example.com
...
BEGIN:PARTICIPANT
CALENDAR-ADDRESS:mailto:xxx@example.com
DTSTAMP:20130226T1104510Z
REASON:https://example.com/reason/van-break-down
COMMENT:Puncture
END:PARTICIPANT
----

=== Task Alerts and Notifications

Different needs to alert or notify task actors of pending or actual
task status changes are recognized:

Alarms:: "VALARM" calendar components operate in the calendar user agent
space to notify the task actor of a pending task state for a task they
are assigned to or are interested in.
+
Current standards (see <<RFC9074>>) indicate "VALARM" calendar components SHOULD be removed
from incoming data and many systems in fact do so. In a task assignment
scenario it may be appropriate for the organizer to be able to set alarms
for the participants. A system implementing these standards may choose to
preserve "VALARM" calendar components but sending a task via some external service may result in
them being removed. This issue is not addressed by this specification.

Escalations:: An escalation or notification to the "Attendee", "Organizer",
or other task actor may be required if a deadline associated with a
task is exceeded or for some other reason. Process Logic identifying
when and who to propagate escalations is the responsibility of the
Task Generating System, e.g., a BPMS.

Notifications:: Task actors (observers) not directly involved in
performing a task, but with a known interest in a given task's status,
can be identified by the "PARTICIPANT" calendar component <<RFC9073>> against certain
components e.g. the "VALARM" calendar component, to identify which task events the
stakeholder/party is interested in. Notifications on shared calendars
will allow task actors to register an interest in changes to tasks
within a calendar (see <<appendix-a>>).

=== Automated Status Changes

A new "TASK-MODE" property is introduced to instruct servers to apply
automated operations for changing the status of a task.
