[[status-reporting]]

== Status Reporting

=== Improved granularity in status reporting information

This document defines a new status component that can be used to
group related information about the status. This might include
information on why (REASON) and when (DTSTAMP) a status has changed.
In addition new status values are specified to
provide for task suspension, failure and preparation.

=== Relating reason and comments to ATTENDEE status changes.

The <<RFC9073>> PARTICIPANT component can be used to provide additional
information about why an ATTENDEE participation status has changed.
The COMMENT property can also
be used to include additional human readable information about why the
associated STATUS or ATTENDEE property changed.

[source]
----
BEGIN:VSTATUS
STATUS:FAILED
REASON:http://example.com/reason/delivery-failed
SUBSTATE:ERROR
DTSTAMP:20130212T120000Z
COMMENT:Breakdown
END:VSTATUS

ATTENDEE;PARTSTAT=FAILED:mailto:xxx@example.com
...
BEGIN:PARTICIPANT
CALENDAR-ADDRESS:mailto:xxx@example.com
DTSTAMP:20130226T1104510Z
REASON:http://example.com/reason/van-break-down
COMMENT:Puncture
END:PARTICIPANT
----

=== Comments associated to reasons and status changes

Multiple comments and reasons may have the same status. As situations
chnage further VSTATUS components can be added to provide additional
information..

[source]
----
CONCEPT:http://example.com/task/delivery
BEGIN:VSTATUS
STATUS:FAILED
SUBSTATE:ERROR
DTSTAMP:20220212T104900Z
COMMENT:Out of time
END:VSTATUS
BEGIN:VSTATUS
STATUS:FAILED
COMMENT:Traffic Accident on E44
REASON:http://example.com/reason/traffic
DTSTAMP:20220212T110451Z
END:VSTATUS
BEGIN:VSTATUS
STATUS:FAILED
COMMENT:Arrived after office hours
REASON:http://example.com/reason/closed
DTSTAMP:20220212T180451Z
END:VSTATUS
----

=== Task Alerts and Notifications

Different needs to alert or notify task actors of pending or actual
task status changes are recognized:

[horizontal]
Alarms:: Alarms (VLARM components) operate in the calendar user agent
space to notify the task actor of a pending task state for a task they
are assigned to or are interested in. Note: there is no constraint in
the current standards on the propagation of alarms specified on
calendar objects by organizers to individual attendees.

Escalations:: An escalation or notification to the ATTENDEE, ORGANIZER,
or other task actor may be required if a deadline associated with a
task is exceeded or for some other reason. Process Logic identifying
when and who to propagate escalations to is the responsibility of the
Task Generating System, e.g., a BPMS.

Notifications:: Task actors (observers) not directly involved in
performing a task but with a known interest in a given task's status
can be identified by the ASSOCIATE property [Doug214] against certain
components e.g. ALARM, to identify which task events the
stakeholder/party is interested in. Notifications on shared calendars
will allow task actors to register an interest in changes to tasks
within a calendar (see <<appendix-a>>).

=== Automated Status Changes

A new property, TASK-MODE, is introduced to instruct servers to apply
automated operations for changing the status of a task.
