[[new-properties]]

== New Properties

[[prop-estimated-duration]]
=== Estimated Duration

Property Name:: ESTIMATED-DURATION

Purpose:: This property specifies the estimated positive duration of time the corresponding task will take to complete.

Value Type::  DURATION

Property Parameters:: IANA and non-standard property parameters can be specified on this property.

Conformance:: This property can be specified in "VTODO" calendar components.

Format Definition:: This property is defined by the following notation:

[source,bnf]
----
est-duration  = "ESTIMATED-DURATION" durparam ":" dur-value CRLF
                ;consisting of a positive duration of time.

durparam      = *(";" other-param)
----

Description:: In a "VTODO" calendar component the property MAY be used to specify the estimated duration for the to-do, with or without an explicit time window in which the event should be started and completed.  When present, DTSTART and DUE/DURATION represent the window in which the task can be performed. ESTIMATED-DURATION SHOULD be passed from ORGANIZER to ATTENDEE in iTIP <<RFC5546>> messages.

Example:: The following is an example of this property that specifies an interval of time of exactly one hour:

[source]
----
ESTIMATED-DURATION:PT1H
----

[[prop-reason]]
=== Reason

Property name::  REASON

Purpose:: To indicate the reason for a change in status of a task or
attendee participation status.

Value Type::  URI

Property Parameters:: IANA and non-standard property parameters can be specified on this property.

Conformance:: This property can be specified in "VSTATUS" and PARTICIPANT calendar components.

Format Definition:: This property is defined by the following notation:

[source,bnf]
----
reason      = "REASON" reasonparam ":" uri CRLF

reasonparam = *(";" other-param)
----

Description:: This property allows the change in status of a
task or participant status to be qualified by the reason for the change
with a codified reason. Typically, reasons are defined within the
context of the task type and therefore SHOULD include the name-space
of the authority defining the task. Common reason codes are IANA
registered and do not have a name-space prefix.

Example::

[source]
----
REASON:https://example.com/reason/delivered-on-time

REASON:out-of-office
----

[[prop-sub-state]]
=== Sub-State

Property name:: SUBSTATE

Purpose:: To provide additional granularity of task status for e.g.
IN-PROCESS.

Value Type::  TEXT

Property Parameters:: IANA and non-standard property parameters can be specified on this property.

Conformance:: This property can be specified in a "VSTATUS" calendar component.

Format Definition:: This property is defined by the following notation:

[source,bnf]
----
substate          = "SUBSTATE" substateparam ":" substatevalue CRLF

substateparam     = *(";" other-param)

substatevalue       = ("OK"        ; everything is fine(the default)
                     / "ERROR"     ; something is wrong (the REASON
                     ;               code explains why)
                     / "SUSPENDED" ; waiting on some other task to
                     ;               complete or availability of a
                     ;               resource (REASON code explains
                     ;               why)
                     / iana-token) ; Other IANA-registered type
----

Description:: The sub-state property allows additional qualification
and granularity of states to be recorded, in particular for the
IN-PROCESS state. It allows individual sub-states to be recorded
without the need to define and publish a sub-task associated with a
parent task purely to track that a particular state has been reached.
This property also allows parallel states to be expressed e.g. that a
task has been suspended at whatever state it has reached.

Example::

[source]
----
BEGIN:VSTATUS
STATUS:FAILED
REASON:https://example.com/reason/no-one-home
SUBSTATE:ERROR
END:VSTATUS

BEGIN:VSTATUS
STATUS:IN-PROCESS
REASON:https://example.com/reason/paint-drying
SUBSTATE:SUSPENDED
END:VSTATUS
----

[[prop-task-mode]]
=== Task Mode

Property Name:: TASK-MODE

Purpose:: This property specifies automatic operations that servers
acting on behalf of the organizer apply to tasks based on changes in
attendee status (PARTSTAT).

Value Type:: TEXT

Property Parameters:: IANA and non-standard property parameters can be specified on this property.

Conformance:: This property can be specified zero or more times in a "VTODO" calendar component.

Format Definition:: This property is defined by the following notation:

[source,bnf]
----
task-mode   = "TASK-MODE taskmodeparam ":" taskvalue
              *("," taskvalue) CRLF

taskvalue   = "AUTOMATIC-COMPLETION" ; set STATUS completed
                ;if all attendees have completed
                / "AUTOMATIC-FAILURE"
                / "SERVER"
                / "CLIENT"
                / iana-token
                / x-name

taskmodeparam      = *(";" other-param)
----

Description:: In a "VTODO" calendar component this property MAY be
used to indicate to servers how they can automatically change the
state of the task based on iTIP replies from Attendees. For example,
the server can automatically set the overall task status to COMPLETED
when every attendee has marked their own status (PARTSTAT) as COMPLETED,
or the server could mark the task as FAILED if its DUE date passes
without it being completed. TASK-MODE processing is performed on the organizer's copy of the task.

To set the status, add a VSTATUS component as specified in <<vstatus>>.

The property value is a list of one or more IANA registered tokens that defines modes to be used for the task. This specification defines three modes which are described in the following subsections.

Examples::

[source]
----
TASK-MODE:AUTOMATIC-COMPLETION,AUTOMATIC-FAILURE
TASK-MODE:SERVER
TASK-MODE:AUTOMATIC-FAILURE
----

[[task-mode-automatic-completion]]
AUTOMATIC-COMPLETION Task Mode::

The task mode value "AUTOMATIC-COMPLETION" indicates to the server
that it can change the "VTODO" component's status to "COMPLETED" as
soon as all ATTENDEEs in the task have replied with a "PARTSTAT"
parameter set to "COMPLETED".

[[task-mode-automatic-failure]]
AUTOMATIC-FAILURE Task Mode::

The task mode value "AUTOMATIC-FAILURE" indicates to the server that
it SHOULD change the "VTODO" component's status to "FAILED" if either:

. the PARTSTAT of one ATTENDEE is set to FAILED; or

. the current time is past the effective due date of the component and the task has not yet been completed.

NOTE: The effective due date is either the "DUE" property value or the
combination of the "DTSTART" and "DURATION" property values.


[[task-mode-client]]
CLIENT Task Mode::

The task mode value "CLIENT" is an instruction to the server to honour
the status set by the client.

[[task-mode-server]]
SERVER Task Mode::

The task mode value "SERVER" indicates to the server that it can change
the "VTODO" component's status to an appropriate value, based on
implementation defined "business rules", as ATTENDEE responses are
processed or as deadlines related to the task pass.
+
The server can add this property to a "VTODO" component to indicate to
the client that it will be managing the status.

