
[[property-extensions]]

== Property Extensions and Clarifications

[[prop-ext-duration]]
=== Updated DURATION Property definition

<<RFC5545>> section 3.6.2 introduced a constraint on the duration property requiring
that a DURATION MUST be accompanied by a DTSTART.
This constraint is dropped reverting to the situation as specified
previously.

Thus the text:

----
                  ; Either 'due' or 'duration' MAY appear in
                  ; a 'todoprop', but 'due' and 'duration'
                  ; MUST NOT occur in the same 'todoprop'.
                  ; If 'duration' appear in a 'todoprop',
                  ; then 'dtstart' MUST also appear in
                  ; the same 'todoprop'.
----

is replaced by

----
                  ; Either 'due' or 'duration' MAY appear in
                  ; a 'todoprop', but 'due' and 'duration'
                  ; MUST NOT occur in the same 'todoprop'.
----

This allows a VTODO to only have a DURATION property.

Furthermore, the following text:

----
     A "VTODO" calendar component without the "DTSTART" and "DUE" (or
     "DURATION") properties specifies a to-do that will be associated
     with each successive calendar date, until it is completed.
----

is replaced by

----
     A "VTODO" calendar component without the "DTSTART" and "DUE"
     properties specifies a to-do that will be associated
     with each successive calendar date, until it is completed.
----

[[prop-ext-status]]
=== Redefined STATUS Property

The Status property is defined in <<RFC5545, section=3.8.1.11>>. This
specification extends that property to include new values
associated with VTODO iCalendar components (See Appendix A for
examples of the task state lifecycle).

Format Definition:: The "STATUS" property parameter list is augmented
as follows:

[source,bnf]
----
statvalue-todo = / "PENDING"    ;Indicates a to-do has been
                                ;created and accepted, but has
                                ; not yet started.
                / "FAILED"      ;Indicates to-do has failed.
;Extended status values for "VTODO" calendar component.
----

Description:

PENDING - A to-do has been created and accepted but has not yet
started and is ready
to start subject to other dependencies (e.g. preceding task or
DTSTART). This is the default state.

FAILED - to-do has failed and may need some follow-up from the
organizer to re-schedule or cancel

Example: The following is an example of this property for a "VTODO"
calendar component:

[source]
----
STATUS:FAILED
----
