==== The PUBLISH method

This method is valid for all component types and is an
unsolicited posting of an iCalendar object.  Any CU may add published
components to their calendar.  The "ORGANIZER" property MUST be present in a
published iCalendar component.  "Attendees" MUST NOT be present.  Its
expected usage is for encapsulating an arbitrary event as an
iCalendar object.  The "Organizer" may subsequently update (with
another "PUBLISH" method), add instances to (with an "ADD" method),
or cancel (with a "CANCEL" method) a previously published calendar component.

As many properties as are required to define
the component SHOULD be sent and MUST follow the contraints defined in <<RFC5546>>.

In particular the SEQUENCE property MUST be present if the value is greater than 0.

==== Publishing VFREEBUSY

The "PUBLISH" method for a "VFREEBUSY" calendar component is used to
publish busy time data.  The method may be sent from one CU to any
other.  The purpose of the method is to provide a way to send
unsolicited busy time data.  That is, the busy time data is not being
sent as a "REPLY" to the receipt of a "REQUEST" method.

The "ORGANIZER" property MUST be specified in the busy time
information.  The value is the CU address of the originator of the
busy time information.

The busy time information within the iCalendar object MAY be grouped
into more than one "VFREEBUSY" calendar component.  This capability
allows busy time periods to be grouped according to some common
periodicity, such as a calendar week, month, or year.  In this case,
each "VFREEBUSY" calendar component MUST include the "ORGANIZER",
"DTSTART", and "DTEND" properties in order to specify the source of
the busy time information and the date and time interval over which
the busy time information covers.


