
[bibliography]
= Normative References

++++

<reference anchor="RFC5545" target="https://www.rfc-editor.org/info/rfc5545">
<front>
<title>
Internet Calendaring and Scheduling Core Object Specification (iCalendar)
</title>
<author initials="B." surname="Desruisseaux" fullname="B. Desruisseaux" role="editor">
<organization/>
</author>
<date year="2009" month="September"/>
<abstract>
<t>
This document defines the iCalendar data format for representing and exchanging calendaring and scheduling information such as events, to-dos, journal entries, and free/busy information, independent of any particular calendar service or protocol. [STANDARDS-TRACK]
</t>
</abstract>
</front>
<seriesInfo name="RFC" value="5545"/>
<seriesInfo name="DOI" value="10.17487/RFC5545"/>
</reference>

<reference anchor="RFC2119" target="https://www.rfc-editor.org/info/rfc2119">
<front>
<title>
Key words for use in RFCs to Indicate Requirement Levels
</title>
<author initials="S." surname="Bradner" fullname="S. Bradner">
<organization/>
</author>
<date year="1997" month="March"/>
<abstract>
<t>
In many standards track documents several words are used to signify the requirements in the specification. These words are often capitalized. This document defines these words as they should be interpreted in IETF documents. This document specifies an Internet Best Current Practices for the Internet Community, and requests discussion and suggestions for improvements.
</t>
</abstract>
</front>
<seriesInfo name="BCP" value="14"/>
<seriesInfo name="RFC" value="2119"/>
<seriesInfo name="DOI" value="10.17487/RFC2119"/>
</reference>

<reference anchor="RFC5988" target="https://www.rfc-editor.org/info/rfc5988">
<front>
<title>Web Linking</title>
<author initials="M." surname="Nottingham" fullname="M. Nottingham">
<organization/>
</author>
<date year="2010" month="October"/>
<abstract>
<t>
This document specifies relation types for Web links, and defines a registry for them. It also defines the use of such links in HTTP headers with the Link header field. [STANDARDS-TRACK]
</t>
</abstract>
</front>
<seriesInfo name="RFC" value="5988"/>
<seriesInfo name="DOI" value="10.17487/RFC5988"/>
</reference>

<reference anchor="W3C.CR-skos-reference-20090317" target="http://www.w3.org/TR/2009/CR-skos-reference-20090317">
<front>
<title>
SKOS Simple Knowledge Organization System Reference
</title>
<author initials="S." surname="Bechhofer" fullname="Sean Bechhofer">
<organization/>
</author>
<author initials="A." surname="Miles" fullname="Alistair Miles">
<organization/>
</author>
<date month="March" day="17" year="2009"/>
</front>
<seriesInfo name="World Wide Web Consortium CR" value="CR-skos-reference-20090317"/>
<format type="HTML" target="http://www.w3.org/TR/2009/CR-skos-reference-20090317"/>
</reference>

<reference anchor="W3C.WD-xptr-xpointer-20021219" target="http://www.w3.org/TR/2002/WD-xptr-xpointer-20021219">
<front>
<title>XPointer xpointer() Scheme</title>
<author initials="S." surname="DeRose" fullname="Steven DeRose">
<organization/>
</author>
<author initials="R." surname="Daniel" fullname="Ron Daniel">
<organization/>
</author>
<author initials="E." surname="Maler" fullname="Eve Maler">
<organization/>
</author>
<date month="December" day="19" year="2002"/>
</front>
<seriesInfo name="World Wide Web Consortium WD" value="WD-xptr-xpointer-20021219"/>
<format type="HTML" target="http://www.w3.org/TR/2002/WD-xptr-xpointer-20021219"/>
</reference>

<reference anchor="I-D.daboo-caldav-attachments">
<front>
<title>CalDAV Managed Attachments</title>
<author initials="C" surname="Daboo" fullname="Cyrus Daboo">
<organization/>
</author>
<author initials="A" surname="Quillaud" fullname="Arnaud Quillaud">
<organization/>
</author>
<date month="February" day="5" year="2014"/>
<abstract>
<t>
This specification defines an extension to the calendar access protocol (CalDAV) to allow attachments associated with iCalendar data, to be stored and managed on the server.
</t>
</abstract>
</front>
<seriesInfo name="Internet-Draft" value="draft-daboo-caldav-attachments-03"/>
<format type="TXT" target="http://www.ietf.org/internet-drafts/draft-daboo-caldav-attachments-03.txt"/>
</reference>
++++

//bibliography::norm[]
////
[bibliography]
= Informative References

//bibliography::info[]
//++++
//include::../references/informative/*.xml[]
//++++
////
