source "https://rubygems.org"

gem "asciidoctor-csd", git: "https://github.com/riboseinc/asciidoctor-csd"
gem "asciidoctor-iso", git: "https://github.com/riboseinc/asciidoctor-iso"
# gem "asciidoctor-rfc", path: "~/src/asciidoctor-rfc"
gem "asciidoctor-bibliography", git: "https://github.com/riboseinc/asciidoctor-bibliography"
