
[[flow]]
== Flow

=== Publication created within publisher
[TODO: WIP to be discussed]

=== Subscriber subscribes a publication
To subscribe a publication, a person or machine submits a subscription request
to a deliverer of the publication. When the deliverer receives the subscription
request, it MUST check whether the person or machine for the permission to the
publication.

If the person or machine is permitted to subscribe to the publication, the
deliverer MUST respond with a success response, and any publication item posted
to the publication afterwards MUST be delivered to the subscriber as a
subscribed item according to the newly created subscription.

If the person or machine is NOT permitted to subscribe to the publication, the
deliverer MUST respond with a failure response, and any publication item posted
to the publication afterwards MUST NOT be delivered to the person or machine.

=== Publishing actor posts a publication item
To post a publication item, a publishing actor sends a publication request to
the publisher. A publication request SHALL contain the id of the publication
and a publication item.

When a publisher receives a publication request, the publisher MUST check the
publishing actor for its eligibility to post a publication item. The publisher
MUST also check the data in the publication item of whether its item type and
format are both supported by the publication.

If all the checks are truthy, the publisher MUST respond with a success
response, and the publication item MUST be transmitted to the deliverer by any
mean in order to transform the publication item into subscribed item and
deliver

If any of the checks found falsy, the publisher MUST respond with a failure
response, and the publication item MUST be ignored and not further processed.


=== Publication item transforms into subscribed items
When the deliverer receives the publication item posted to a publication,
the deliverer MUST process for each subscription associated with the
publication. For each subscription associated, the deliverer MUST transform the
publication item into a subscribed item by serializing the data in the
publication item into serialized data with the serializer given in the
subscription.

=== Subscribers receive subscribed items through delivery channels defined
The subscribed item then delivers to the subscriber according to the delivery
channels defined in the subscription. The subscribers get the subscribed item
through the delivery channels.

=== Subscriber unsubscribes a publication
To stop receiving subscribed items from a subscription, the subscriber can
unsubscribe from the subscription. To unsubscribe, the subscriber sends
an unsubscription request with the subscription id provided to the deliverer.
The deliverer then remove the subscription for the subscriber.

After the removal of a subscription, the deliverer MUST NOT deliver any item
to the subscriber about the subscription removed.


