[[redefined_property_related_to]]
= Redefined RELATED-TO Property

[[related-to]]
==  RELATED-TO

Property name: :: RELATED-TO

Purpose: :: This property is used to represent a relationship or
   reference between one calendar component and another.  The
   definition here extends the definition in  
   <<RFC5545,section 3.8.4.5>> by allowing URI or UID values and a GAP parameter.

Value type: :: URI, UID or TEXT

Property Parameters: :: Relationship type, IANA and non-standard
   property parameters can be specified on this property.

Conformance: :: This property MAY be specified in any iCalendar
   component.

Description: :: By default or when VALUE=UID is specified, the property
   value consists of the persistent, globally unique identifier of
   another calendar component.  This value would be represented in a
   calendar component by the "UID" property.
+
By default, the property value points to another calendar
   component that has a PARENT relationship to the referencing
   object.  The "RELTYPE" property parameter is used to either
   explicitly state the default PARENT relationship type to the
   referenced calendar component or to override the default PARENT
   relationship type and specify either a CHILD or SIBLING
   relationship or a temporal relationship.
+
The PARENT relationship indicates that the calendar component is a
   subordinate of the referenced calendar component.  The CHILD
   relationship indicates that the calendar component is a superior
   of the referenced calendar component.  The SIBLING relationship
   indicates that the calendar component is a peer of the referenced
   calendar component.
+
The FINISHTOSTART, FINISHTOFINISH, STARTTOFINISH or STARTTOSTART
   relationships define temporal relationships as specified in the
   reltype parameter definition.
+
Changes to a calendar component referenced by this property can
   have an implicit impact on the related calendar component.  For
   example, if a group event changes its start or end date or time,
   then the related, dependent events will need to have their start
   and end dates changed in a corresponding way.  Similarly, if a
   PARENT calendar component is cancelled or deleted, then there is
   an implied impact to the related CHILD calendar components.  This
   property is intended only to provide information on the
   relationship of calendar components.  It is up to the target
   calendar system to maintain any property implications of this
   relationship.

Format Definition: ::
+
This property is defined by the following notation:
+
[source,bnf]
----
  related    = "RELATED-TO" relparam ( ":" text ) /
               (
                 ";" "VALUE" "=" "UID"
                 ":" uid
               )
               (
                 ";" "VALUE" "=" "URI"
                 ":" uri
               )
               CRLF

  relparam   = *(
              ;
              ; The following are OPTIONAL,
              ; but MUST NOT occur more than once.
              ;
              (";" reltypeparam) /
              (";" gapparam) /
              ;
              ; The following is OPTIONAL,
              ; and MAY occur more than once.
              ;
              (";" other-param)
              ;
              )
----

Example: ::
+
The following are examples of this property.
+
[source]
----
  RELATED-TO:jsmith.part7.19960817T083000.xyzMail@example.com

  RELATED-TO:19960401-080045-4000F192713-0052@example.com

  RELATED-TO;VALUE=URI;RELTYPE=STARTTOFINISH:
   http://example.com/caldav/user/jb/cal/
   19960401-080045-4000F192713.ics
----

